### ISSUE TITLE
Is this project still actively developed

### ISSUE THREAD

**Issue by nickbe** [cutec-chris/promet-erp#74]
Just a question to make sure I'm not investing time in a dead system :)

**Comment by cutec-chris** [comment]
Take a look at the commits :)
https://github.com/cutec-chris/promet-erp/commits/master

Ive read your Forum Posts also already but today i dont get the time to take a look.

**Comment by nickbe** [comment]
Hey Chris,

Entschuldige, ich wollte Dir nicht auf die Füße treten!
Nach einem Blick auf die Commits, ziehe ich die Frage zurück, bzw. ändere sie: 
Wann arbeitest Du NICHT am System 😀 ?

Wir werden die Wawi ausführlich testen und versuchen Fehler so detailliert wie möglich an Dich weiter zu melden. Ist es Dir lieber im Forum oder hier via GitHub?

**Comment by cutec-chris** [comment]
Kommt beides letztendlich per Mail bei mir an, ist mir also völlig gleich :)
Ich schau mir erstmal die groben Probleme an, (das mit den Access Violations ist definitiv nicht normal) und dann können wir auch mal ne TeamViewer Session machen oder ähnliches.

**Comment by cutec-chris** [comment]
Ach ja noch zur Frage: hab das Glück das teilweise Hauptberuflich machen zu können. Deshalb passiert da eigentlich immer was. Wenn ihr vorhabt selbst in Richtung Features was zu machen würde sich das super ergänzen. Bei Fehlern bin ich eigentlich immer recht schnell. Wenn ich eure Features nicht nin meine Konzepte intigrieren kann wirds naturgemäss etwas zäh.

**Comment by nickbe** [comment]
Alles klar. Sehr gerne. 
Könnte das an den diversen C Runtimes liegen die Microsoft so verteilt ?
Ich bin heute auch eher im Freizeitmodus, aber Deine Wawi hat uns auf den ersten Blick so gefallen, dass wir nicht wiederstehen konnten ein wenig zu testen.

Eine Frage: Wäre es denkbar die Nummernkreise um eine Datums/Zeit Kodierung zu ergänzen?

**Comment by cutec-chris** [comment]
Du meinst eine Art logging ?
Ich hab vor die Vergabe der Nummernkreise noch über eine separate Tabelle zu ziehen so das man nachvollziehen kann wer wann welchen Nummernkreis freigegeben hat. Wenn euch das reicht könnt ich das im nächsten Monat sicher irgendwo mit unterbringen.

**Comment by nickbe** [comment]
Nein ich meinte Nummerkreise für z.B. Rechnungen in der Form: YYDDDHHMMSSMS wobei die Ausgabe bei uns bis jetzt in Blöcken formatiert wird: YYDD-DHHMM-SSMS, wobei DDD der jahrestag ist und MS Millisekunden. Sofern kurz geprüft wird ob zB eine Rechnungs-Nummer bereits vergeben wurde um dann eine weitere zu generieren wäre das momentan für uns das Killerfeature.

**Comment by cutec-chris** [comment]
Das sollte kein Thema sein. Mach mal ne Issue dafür auf, dann bekommst du auch mit wenns "behoben" ist.

**Comment by nickbe** [comment]
Ey, das wäre der Hammer. 
Die Nummern z.B. für Rechnungen sehen dann bei uns z.B. so aus: R1802-3143-0153. Wir nehmen immer nur die erste Ziffer der Millisekunden, können also pro Sekunden 10 Rechnungen erzeugen.

Ich schreibe heute Abend ein Ticket und melde mich nach dem Feiertag wieder. 
Danke und sonnigen Feiertag schon mal.

**Comment by nickbe** [comment]
Das hört sich doch cool an. Yep, das Feldarten-Dropdown habe ich schon gesehen. 
Hier ist die Original-Formel unserer Nummerkreise:
YYHHHHMMSSN, wobei HHHH, der (Tag des Jahres * Stunde) + 1024 ist. Du machst also aus Monat, Tag und Stunde insgesamt einen vierstelligen Wert von 1024 bis 9784.

Du endest dann bei Rechnungsnummern wie: YYH-HHHM-MSSN (N wieder für die erste stelle Milisek.)
Beispiel: R174-1831-6246. 
Für Kundennummern haben wir die Sekunden belassen und die Formatierung in 1741-831-624 geändert. Projekte ebenfalls pro Sekunde, aber als 1741-83-1624 dargestellt.
Somit kannst Du rein optisch schon erkennen um was für eine Art der Nummer es sich handelt, 

Ansonsten ist der Standard inklusive der ersten Stelle Milllisekunde Timestamp auch ohne Kürzung auf Sekunden gut.
