### ISSUE TITLE
Spalte Seriennummer in der Liste der Artikel nicht auswählbar

### ISSUE THREAD

**Issue by nickbe** [cutec-chris/promet-erp#76]
Ich bin mir jedoch sicher dass ich die Spalte in der portable Version schon mal hatte.

**Comment by cutec-chris** [comment]
Seriennummer gibts in der Artikeltabelle nicht, lediglich USESERIAL (Serienummernpflicht) Seriennummern sind in einer seperaten Tabelle abgelegt. In der Auftragsposition gibts Seriennummer, verwechselst das vllt damit ?

**Comment by nickbe** [comment]
Ah danke. Ist eigentlich logisch (*Facepalm*)
