### ISSUE TITLE
Fehler in Sofortrechnung

### ISSUE THREAD

**Issue by nickbe** [cutec-chris/promet-erp#78]
Folgender Vorgang: Erstellen einer Sofortrechnung, Eingabe eines neuen Kunden, danach in den Positionen munteres Tippen im Feld Text -> System findet vorhandenen Artikel -> Mit der Maus auswählen -> Crash

SQL Error: bad parameter or other API misuse (constraint failed)
Original exception: SQL Error: bad parameter or other API misuse (constraint failed)
Description

**Comment by nickbe** [comment]
Das selbe passiert wenn ich den Artikel aus der Suchliste hinzufüge.
Der betreffende Artikel wurde mit dem Status (SM) versehen und beim Speichern des Statuses gab es ebenfalls eine Fehlermeldung. Artikel schein jedoch vorhanden zu sein -> seine Benutzung führt jedoch zu dem vorliegenden Fehler.

**Comment by cutec-chris** [comment]
In der help.db kann ichd as erstmal nicht nachstellen, muss ich mal mit ner frischen db probieren. Aber heut nichtmehr.

**Comment by nickbe** [comment]
Auch das hab' ich gemacht ja.

**Comment by cutec-chris** [comment]
gibts das Problem in der aktuellen version noch ?
